// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// APICreateEventParams is parameters of Api_createEvent operation.
type APICreateEventParams struct {
	Cookie OptString `json:",omitempty,omitzero"`
}

func unpackAPICreateEventParams(packed middleware.Parameters) (params APICreateEventParams) {
	{
		key := middleware.ParameterKey{
			Name: "Cookie",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Cookie = v.(OptString)
		}
	}
	return params
}

func decodeAPICreateEventParams(args [0]string, argsEscaped bool, r *http.Request) (params APICreateEventParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Cookie.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Cookie",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCookieVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCookieVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cookie.SetTo(paramsDotCookieVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Cookie",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APIGetEventsParams is parameters of Api_getEvents operation.
type APIGetEventsParams struct {
	Cookie OptString `json:",omitempty,omitzero"`
	Title  OptString `json:",omitempty,omitzero"`
	Limit  OptInt64  `json:",omitempty,omitzero"`
	Offset OptInt64  `json:",omitempty,omitzero"`
}

func unpackAPIGetEventsParams(packed middleware.Parameters) (params APIGetEventsParams) {
	{
		key := middleware.ParameterKey{
			Name: "Cookie",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Cookie = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "title",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Title = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt64)
		}
	}
	return params
}

func decodeAPIGetEventsParams(args [0]string, argsEscaped bool, r *http.Request) (params APIGetEventsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Cookie.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Cookie",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCookieVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCookieVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cookie.SetTo(paramsDotCookieVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Cookie",
			In:   "header",
			Err:  err,
		}
	}
	// Decode query: title.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "title",
			Style:   uri.QueryStyleForm,
			Explode: false,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTitleVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTitleVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Title.SetTo(paramsDotTitleVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "title",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: false,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt64(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: false,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt64(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIHealthParams is parameters of Api_health operation.
type APIHealthParams struct {
	Cookie OptString `json:",omitempty,omitzero"`
}

func unpackAPIHealthParams(packed middleware.Parameters) (params APIHealthParams) {
	{
		key := middleware.ParameterKey{
			Name: "Cookie",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Cookie = v.(OptString)
		}
	}
	return params
}

func decodeAPIHealthParams(args [0]string, argsEscaped bool, r *http.Request) (params APIHealthParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Cookie.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Cookie",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCookieVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCookieVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cookie.SetTo(paramsDotCookieVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Cookie",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APILoginParams is parameters of Api_login operation.
type APILoginParams struct {
	Cookie OptString `json:",omitempty,omitzero"`
}

func unpackAPILoginParams(packed middleware.Parameters) (params APILoginParams) {
	{
		key := middleware.ParameterKey{
			Name: "Cookie",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Cookie = v.(OptString)
		}
	}
	return params
}

func decodeAPILoginParams(args [0]string, argsEscaped bool, r *http.Request) (params APILoginParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Cookie.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Cookie",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCookieVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCookieVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cookie.SetTo(paramsDotCookieVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Cookie",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APILogoutParams is parameters of Api_logout operation.
type APILogoutParams struct {
	Cookie OptString `json:",omitempty,omitzero"`
}

func unpackAPILogoutParams(packed middleware.Parameters) (params APILogoutParams) {
	{
		key := middleware.ParameterKey{
			Name: "Cookie",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Cookie = v.(OptString)
		}
	}
	return params
}

func decodeAPILogoutParams(args [0]string, argsEscaped bool, r *http.Request) (params APILogoutParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Cookie.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Cookie",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCookieVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCookieVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cookie.SetTo(paramsDotCookieVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Cookie",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APIRegisterParams is parameters of Api_register operation.
type APIRegisterParams struct {
	Cookie OptString `json:",omitempty,omitzero"`
}

func unpackAPIRegisterParams(packed middleware.Parameters) (params APIRegisterParams) {
	{
		key := middleware.ParameterKey{
			Name: "Cookie",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Cookie = v.(OptString)
		}
	}
	return params
}

func decodeAPIRegisterParams(args [0]string, argsEscaped bool, r *http.Request) (params APIRegisterParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Cookie.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Cookie",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCookieVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCookieVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cookie.SetTo(paramsDotCookieVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Cookie",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// APISessionParams is parameters of Api_session operation.
type APISessionParams struct {
	Cookie OptString `json:",omitempty,omitzero"`
}

func unpackAPISessionParams(packed middleware.Parameters) (params APISessionParams) {
	{
		key := middleware.ParameterKey{
			Name: "Cookie",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.Cookie = v.(OptString)
		}
	}
	return params
}

func decodeAPISessionParams(args [0]string, argsEscaped bool, r *http.Request) (params APISessionParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Cookie.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Cookie",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCookieVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCookieVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cookie.SetTo(paramsDotCookieVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Cookie",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
