// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APICreateEventOperation        OperationName = "APICreateEvent"
	APICreateEventReviewOperation  OperationName = "APICreateEventReview"
	APIDislikeEventOperation       OperationName = "APIDislikeEvent"
	APIGetEventOperation           OperationName = "APIGetEvent"
	APIGetEventReviewsOperation    OperationName = "APIGetEventReviews"
	APIGetEventsOperation          OperationName = "APIGetEvents"
	APIGetRecommendationsOperation OperationName = "APIGetRecommendations"
	APIGetUserOperation            OperationName = "APIGetUser"
	APIGetUserEventsOperation      OperationName = "APIGetUserEvents"
	APIGetUsersOperation           OperationName = "APIGetUsers"
	APIHealthOperation             OperationName = "APIHealth"
	APILikeEventOperation          OperationName = "APILikeEvent"
	APILoginOperation              OperationName = "APILogin"
	APILogoutOperation             OperationName = "APILogout"
	APIPatchEventOperation         OperationName = "APIPatchEvent"
	APIRegisterOperation           OperationName = "APIRegister"
	APISessionOperation            OperationName = "APISession"
	APIUpdateEventReviewOperation  OperationName = "APIUpdateEventReview"
)
