// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIHealth implements Api_health operation.
//
// Healthcheck with session.
//
// GET /health
func (UnimplementedHandler) APIHealth(ctx context.Context, params APIHealthParams) (r *HealthResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// APISession implements Api_session operation.
//
// Create or extend user's session.
//
// POST /session
func (UnimplementedHandler) APISession(ctx context.Context, params APISessionParams) (r APISessionRes, _ error) {
	return r, ht.ErrNotImplemented
}
