// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APICreateEvent implements Api_createEvent operation.
//
// Create a new event.
//
// POST /events
func (UnimplementedHandler) APICreateEvent(ctx context.Context, req *CreateEventRequest, params APICreateEventParams) (r APICreateEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APICreateEventReview implements Api_createEventReview operation.
//
// Create a review for an event.
//
// POST /events/{event_id}/reviews
func (UnimplementedHandler) APICreateEventReview(ctx context.Context, req *CreateReviewRequest, params APICreateEventReviewParams) (r APICreateEventReviewRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIDislikeEvent implements Api_dislikeEvent operation.
//
// Dislike event by id.
//
// POST /events/{id}/dislike
func (UnimplementedHandler) APIDislikeEvent(ctx context.Context, params APIDislikeEventParams) (r APIDislikeEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIGetEvent implements Api_getEvent operation.
//
// Get event by id.
//
// GET /events/{id}
func (UnimplementedHandler) APIGetEvent(ctx context.Context, params APIGetEventParams) (r APIGetEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIGetEventReviews implements Api_getEventReviews operation.
//
// Get reviews for an event.
//
// GET /events/{event_id}/reviews
func (UnimplementedHandler) APIGetEventReviews(ctx context.Context, params APIGetEventReviewsParams) (r APIGetEventReviewsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIGetEvents implements Api_getEvents operation.
//
// Get events with filtering and pagination.
//
// GET /events
func (UnimplementedHandler) APIGetEvents(ctx context.Context, params APIGetEventsParams) (r APIGetEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIGetRecommendations implements Api_getRecommendations operation.
//
// Get recommended events for user.
//
// GET /recommendations
func (UnimplementedHandler) APIGetRecommendations(ctx context.Context, params APIGetRecommendationsParams) (r APIGetRecommendationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIGetUser implements Api_getUser operation.
//
// Get user by id.
//
// GET /users/{id}
func (UnimplementedHandler) APIGetUser(ctx context.Context, params APIGetUserParams) (r APIGetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIGetUserEvents implements Api_getUserEvents operation.
//
// Get user events.
//
// GET /users/{id}/events
func (UnimplementedHandler) APIGetUserEvents(ctx context.Context, params APIGetUserEventsParams) (r APIGetUserEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIGetUsers implements Api_getUsers operation.
//
// Get users.
//
// GET /users
func (UnimplementedHandler) APIGetUsers(ctx context.Context, params APIGetUsersParams) (r APIGetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIHealth implements Api_health operation.
//
// Healthcheck with session.
//
// GET /health
func (UnimplementedHandler) APIHealth(ctx context.Context, params APIHealthParams) (r *HealthResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// APILikeEvent implements Api_likeEvent operation.
//
// Like event by id.
//
// POST /events/{id}/like
func (UnimplementedHandler) APILikeEvent(ctx context.Context, params APILikeEventParams) (r APILikeEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APILogin implements Api_login operation.
//
// Authenticate user.
//
// POST /auth/login
func (UnimplementedHandler) APILogin(ctx context.Context, req *LoginRequest, params APILoginParams) (r APILoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APILogout implements Api_logout operation.
//
// Logout user.
//
// POST /auth/logout
func (UnimplementedHandler) APILogout(ctx context.Context, params APILogoutParams) (r APILogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIPatchEvent implements Api_patchEvent operation.
//
// Patch event by id.
//
// PATCH /events/{id}
func (UnimplementedHandler) APIPatchEvent(ctx context.Context, req *PatchEventRequest, params APIPatchEventParams) (r APIPatchEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIRegister implements Api_register operation.
//
// Register a new user.
//
// POST /users
func (UnimplementedHandler) APIRegister(ctx context.Context, req *UserRegisterRequest, params APIRegisterParams) (r APIRegisterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APISession implements Api_session operation.
//
// Create or extend user's session.
//
// POST /session
func (UnimplementedHandler) APISession(ctx context.Context, params APISessionParams) (r APISessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIUpdateEventReview implements Api_updateEventReview operation.
//
// Update a review for an event.
//
// PATCH /events/{event_id}/reviews/{review_id}
func (UnimplementedHandler) APIUpdateEventReview(ctx context.Context, req *UpdateReviewRequest, params APIUpdateEventReviewParams) (r APIUpdateEventReviewRes, _ error) {
	return r, ht.ErrNotImplemented
}
