// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIPing implements Api_ping operation.
//
// Ping.
//
// GET /api/ping
func (UnimplementedHandler) APIPing(ctx context.Context) (r APIPingOK, _ error) {
	return r, ht.ErrNotImplemented
}

// APISession implements Api_session operation.
//
// Create or extend user's session.
//
// POST /api/session
func (UnimplementedHandler) APISession(ctx context.Context, params APISessionParams) (r APISessionRes, _ error) {
	return r, ht.ErrNotImplemented
}
