// Code generated by ogen, DO NOT EDIT.
package api

type APICreateEventRes interface {
	aPICreateEventRes()
}

type APIDislikeEventRes interface {
	aPIDislikeEventRes()
}

type APIGetEventRes interface {
	aPIGetEventRes()
}

type APIGetEventsRes interface {
	aPIGetEventsRes()
}

type APIGetUserEventsRes interface {
	aPIGetUserEventsRes()
}

type APIGetUserRes interface {
	aPIGetUserRes()
}

type APIGetUsersRes interface {
	aPIGetUsersRes()
}

type APILikeEventRes interface {
	aPILikeEventRes()
}

type APILoginRes interface {
	aPILoginRes()
}

type APILogoutRes interface {
	aPILogoutRes()
}

type APIPatchEventRes interface {
	aPIPatchEventRes()
}

type APIRegisterRes interface {
	aPIRegisterRes()
}

type APISessionRes interface {
	aPISessionRes()
}
