// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIPing implements Api_ping operation.
	//
	// Ping.
	//
	// GET /api/ping
	APIPing(ctx context.Context) (APIPingOK, error)
	// APISession implements Api_session operation.
	//
	// Create or extend user's session.
	//
	// POST /api/session
	APISession(ctx context.Context, params APISessionParams) (APISessionRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
