// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APICreateEvent implements Api_createEvent operation.
	//
	// Create a new event.
	//
	// POST /events
	APICreateEvent(ctx context.Context, req *CreateEventRequest, params APICreateEventParams) (APICreateEventRes, error)
	// APIDislikeEvent implements Api_dislikeEvent operation.
	//
	// Dislike event by id.
	//
	// POST /events/{id}/dislike
	APIDislikeEvent(ctx context.Context, params APIDislikeEventParams) (APIDislikeEventRes, error)
	// APIGetEvent implements Api_getEvent operation.
	//
	// Get event by id.
	//
	// GET /events/{id}
	APIGetEvent(ctx context.Context, params APIGetEventParams) (APIGetEventRes, error)
	// APIGetEvents implements Api_getEvents operation.
	//
	// Get events with filtering and pagination.
	//
	// GET /events
	APIGetEvents(ctx context.Context, params APIGetEventsParams) (APIGetEventsRes, error)
	// APIGetUser implements Api_getUser operation.
	//
	// Get user by id.
	//
	// GET /users/{id}
	APIGetUser(ctx context.Context, params APIGetUserParams) (APIGetUserRes, error)
	// APIGetUserEvents implements Api_getUserEvents operation.
	//
	// Get user events.
	//
	// GET /users/{id}/events
	APIGetUserEvents(ctx context.Context, params APIGetUserEventsParams) (APIGetUserEventsRes, error)
	// APIGetUsers implements Api_getUsers operation.
	//
	// Get users.
	//
	// GET /users
	APIGetUsers(ctx context.Context, params APIGetUsersParams) (APIGetUsersRes, error)
	// APIHealth implements Api_health operation.
	//
	// Healthcheck with session.
	//
	// GET /health
	APIHealth(ctx context.Context, params APIHealthParams) (*HealthResponseHeaders, error)
	// APILikeEvent implements Api_likeEvent operation.
	//
	// Like event by id.
	//
	// POST /events/{id}/like
	APILikeEvent(ctx context.Context, params APILikeEventParams) (APILikeEventRes, error)
	// APILogin implements Api_login operation.
	//
	// Authenticate user.
	//
	// POST /auth/login
	APILogin(ctx context.Context, req *LoginRequest, params APILoginParams) (APILoginRes, error)
	// APILogout implements Api_logout operation.
	//
	// Logout user.
	//
	// POST /auth/logout
	APILogout(ctx context.Context, params APILogoutParams) (APILogoutRes, error)
	// APIPatchEvent implements Api_patchEvent operation.
	//
	// Patch event by id.
	//
	// PATCH /events/{id}
	APIPatchEvent(ctx context.Context, req *PatchEventRequest, params APIPatchEventParams) (APIPatchEventRes, error)
	// APIRegister implements Api_register operation.
	//
	// Register a new user.
	//
	// POST /users
	APIRegister(ctx context.Context, req *UserRegisterRequest, params APIRegisterParams) (APIRegisterRes, error)
	// APISession implements Api_session operation.
	//
	// Create or extend user's session.
	//
	// POST /session
	APISession(ctx context.Context, params APISessionParams) (APISessionRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
