// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APICreateEventOperation   OperationName = "APICreateEvent"
	APIGetEventOperation      OperationName = "APIGetEvent"
	APIGetEventsOperation     OperationName = "APIGetEvents"
	APIGetUserOperation       OperationName = "APIGetUser"
	APIGetUserEventsOperation OperationName = "APIGetUserEvents"
	APIGetUsersOperation      OperationName = "APIGetUsers"
	APIHealthOperation        OperationName = "APIHealth"
	APILoginOperation         OperationName = "APILogin"
	APILogoutOperation        OperationName = "APILogout"
	APIPatchEventOperation    OperationName = "APIPatchEvent"
	APIRegisterOperation      OperationName = "APIRegister"
	APISessionOperation       OperationName = "APISession"
)
