openapi: 3.0.0
info:
  title: ndbx-service
  version: 0.0.0
tags: []
paths:
  /health:
    get:
      operationId: Api_health
      summary: healthcheck with session
      parameters:
        - $ref: '#/components/parameters/HealthRequest'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            Cookie:
              required: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /session:
    post:
      operationId: Api_session
      summary: create or extend user's session
      parameters:
        - $ref: '#/components/parameters/SessionRequest'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
components:
  parameters:
    HealthRequest:
      name: Cookie
      in: header
      required: false
      schema:
        type: string
    SessionRequest:
      name: Cookie
      in: header
      required: false
      schema:
        type: string
  schemas:
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
servers:
  - url: http://localhost:8080
    description: localhost
    variables: {}
